# Generated by Django 5.0.1 on 2024-02-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='sender',
        ),
    ]
